PBLVII/PBLVII/Controllers/ProgramadoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PBLVII.Models;
using Rotativa;
using Rotativa.Options;

namespace PBLVII.Controllers
{
    public class ProgramadoresController : Controller
    {
        private PBLVIIContext db = new PBLVIIContext();

        // GET: Programadores
        public ActionResult Index()
        {
            return View(db.Programadors.ToList());
        }
   
      public ActionResult RelatorioAtividadesPorProgramador(int id, int? pagina, Boolean? geraPDF)
      {
         var tarefas = db.Tarefas.Where(p => p.ProgramadorId == id ).ToList();
        

         if (geraPDF == true)
         {
            int pgQtdRegistro = 2;
            int pgNav = (pagina ?? 1);

            return View(tarefas.ToPagedList(pgNav, pgQtdRegistro));
         }
         else
         {
            int paginaNumero = 1;
            var pdf = new ViewAsPdf
            {
               ViewName = "RelatorioAtividadesPorProgramador",
               PageSize = Size.A4,
               IsGrayScale = false,
               Model = tarefas.ToPagedList(paginaNumero, tarefas.Count)
            };
            return pdf;
         }
         
      }


      // GET: Programadores/Details/5
      public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programador programador = db.Programadors.Find(id);
            if (programador == null)
            {
                return HttpNotFound();
            }
            return View(programador);
        }

        // GET: Programadores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Programadores/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProgramadorId,Nome,Nivel")] Programador programador)
        {
            if (ModelState.IsValid)
            {
                db.Programadors.Add(programador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(programador);
        }

        // GET: Programadores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programador programador = db.Programadors.Find(id);
            if (programador == null)
            {
                return HttpNotFound();
            }
            return View(programador);
        }

        // POST: Programadores/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProgramadorId,Nome,Nivel")] Programador programador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(programador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(programador);
        }

        // GET: Programadores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programador programador = db.Programadors.Find(id);
            if (programador == null)
            {
                return HttpNotFound();
            }
            return View(programador);
        }

        // POST: Programadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Programador programador = db.Programadors.Find(id);
            db.Programadors.Remove(programador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PBLVII/PBLVII/Controllers/TarefasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PBLVII.Models;
using Rotativa;
using Rotativa.Options;

namespace PBLVII.Controllers
{
   public class TarefasController : Controller
   {
      private PBLVIIContext db = new PBLVIIContext();


      public ActionResult Index()
      {
         var tarefas = db.Tarefas.Include(t => t.Programador);
         return View(tarefas.ToList());
      }

      public ActionResult BuscarTarefaPorPeriodo()
      {
         return View();

      }

      [HttpPost]
      public ActionResult BuscarTarefaPorPeriodo(DateTime dataInicio, DateTime dataFim, int? pagina, Boolean? geraPDF)
      {
         var tarefas = db.Tarefas.Where(i => i.Status == "Done" && i.DataInicio >= dataInicio && i.DataFim <= dataFim).ToList();
         List<Tarefa> tarefass = new List<Tarefa>();
         foreach (var item in tarefas)
         {
            db.Entry(item).Reference(t => t.Programador).Load();
            tarefass.Add(item);
         }
         if (geraPDF == true)
         {
            int pgQtdRegistro = 2;
            int pgNav = (pagina ?? 1);

            return View(tarefas.ToPagedList(pgNav, pgQtdRegistro));
         }
         else
         {
            int paginaNumero = 1;
            var pdf = new ViewAsPdf
            {
               ViewName = "RelatorioTarefasPorPeriodo",
               PageSize = Size.A4,
               IsGrayScale = false,
               Model = tarefas.ToPagedList(paginaNumero, tarefas.Count)
            };
            return pdf;
         }

      }

      // GET: Tarefas/Details/5
      public ActionResult Details(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Tarefa tarefa = db.Tarefas.Find(id);
         if (tarefa == null)
         {
            return HttpNotFound();
         }
         return View(tarefa);
      }

      // GET: Tarefas/Create
      public ActionResult Create()
      {
         ViewBag.ProgramadorId = new SelectList(db.Programadors, "ProgramadorId", "Nome");
         return View();
      }

      // POST: Tarefas/Create
      // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
      // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "TarefaId,Nome,Status,DataInicio,DataFim,ProgramadorId")] Tarefa tarefa)
      {
         if (ModelState.IsValid)
         {
            db.Tarefas.Add(tarefa);
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         ViewBag.ProgramadorId = new SelectList(db.Programadors, "ProgramadorId", "Nome", tarefa.ProgramadorId);
         return View(tarefa);
      }

      // GET: Tarefas/Edit/5
      public ActionResult Edit(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Tarefa tarefa = db.Tarefas.Find(id);
         if (tarefa == null)
         {
            return HttpNotFound();
         }
         ViewBag.ProgramadorId = new SelectList(db.Programadors, "ProgramadorId", "Nome", tarefa.ProgramadorId);
         return View(tarefa);
      }

      // POST: Tarefas/Edit/5
      // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
      // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "TarefaId,Nome,Status,DataInicio,DataFim,ProgramadorId")] Tarefa tarefa)
      {
         if (ModelState.IsValid)
         {
            db.Entry(tarefa).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         ViewBag.ProgramadorId = new SelectList(db.Programadors, "ProgramadorId", "Nome", tarefa.ProgramadorId);
         return View(tarefa);
      }

      // GET: Tarefas/Delete/5
      public ActionResult Delete(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Tarefa tarefa = db.Tarefas.Find(id);
         if (tarefa == null)
         {
            return HttpNotFound();
         }
         return View(tarefa);
      }

      // POST: Tarefas/Delete/5
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(int id)
      {
         Tarefa tarefa = db.Tarefas.Find(id);
         db.Tarefas.Remove(tarefa);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing)
         {
            db.Dispose();
         }
         base.Dispose(disposing);
      }
   }
}

PBLVII/PBLVII/Views/Shared/LayoutRelatorios.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LayoutRelatorios</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body  background="~/img/imagemm.jpg">
    <div class="container">
        <div class="col-md-4 ">
            <img class="img-responsive" src="~/img/senai_bahia.png" alt="Logo Senai">
        </div>
       
        <div class="container" id="fundo">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; Relatório - @DateTime.Now.Year - Let's Que Let's</p>
            </footer>
        </div>

    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PBLVII/PBLVII/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body background="~/img/imagemm.jpg">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Let's Que Let's", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Programador", "Index", "Programadores")</li>
                    <li>@Html.ActionLink("Tarefa", "Index", "Tarefas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" id="fundo">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Let's Que Let's</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>